root = "."
tmp_dir = ".temp"

[build]
  bin = "./.temp/main"
  args_bin = ["-e", "dev"]
  cmd = "go build -o ./.temp/main ./main.go"
  exclude_unchanged = true

[color]
  app = "red"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = true
